Add reboot to the standard mode
githubixx/ansible-role-wireguard pull request #184
Opened 2023-03-08 13:10 UTC by mofelee

It needs to be rebooted to make the WireGuard kernel module available.

2023-03-08 19:30 UTC, githubixx requested changes
Thanks! A few comments inline. Please also update `README.md` accordingly. Also please add an entry to `CHANGELOG.md` about what was changed. As this actually changes the behavior of for the CentOS 7 users it makes sense to have a new major version number. So it would be `14.0.0`.

2023-03-08 19:30 UTC, githubixx commented on tasks/setup-centos-7.yml
> +      register: centos7_yum_updates
```suggestion
      register: wireguard__centos7_yum_updates
```
Internal variables should be prefixed with `wireguard__`.

As you're already on it :wink: : Could you please also add this prefix here:

https://github.com/githubixx/ansible-role-wireguard/blob/17ed7be8f324a9521193e193df3b7d2bb5c7abc5/tasks/setup-centos-7.yml#L68
https://github.com/githubixx/ansible-role-wireguard/blob/17ed7be8f324a9521193e193df3b7d2bb5c7abc5/tasks/setup-centos-7.yml#L74-L75

That was an oversight to not add it. Thanks!

2023-03-08 19:30 UTC, githubixx commented on tasks/setup-centos-7.yml
> +        - centos7_yum_updates.changed is true
```suggestion
        - wireguard__centos7_yum_updates.changed is true
```

2023-03-09 01:13 UTC, mofelee commented
@githubixx 
I think it's okay now.

2023-03-17 01:28 UTC, mofelee commented
In my case, if I don't reboot CentOS 7, it cannot pass through the 'Enable WireGuard kernel module' task.

```bash
> cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

```bash
> uname -a
Linux xx.local 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
> cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
```

```bash
> lsb_release
LSB Version:	:core-4.1-amd64:core-4.1-noarch
```


<img width="1728" alt="CleanShot 2023-03-17 at 09 24 44@2x" src="https://user-images.githubusercontent.com/5069410/225788431-58b2e2b6-1b15-4f8a-aa8b-1515dc523a24.png">


![CleanShot 2023-03-17 at 09 27 10@2x](https://user-images.githubusercontent.com/5069410/225788828-c21ccb49-e9d8-4d2f-b042-b8e032f031be.png)

2023-03-17 01:56 UTC, mofelee commented
<img width="924" alt="CleanShot 2023-03-17 at 09 54 24@2x" src="https://user-images.githubusercontent.com/5069410/225792228-d1b23bbf-c4f4-4622-8ba7-f65657863087.png">

I've reproduced this error on this ISO file.

http://bay.uchicago.edu/centos-vault/7.6.1810/isos/x86_64/CentOS-7-x86_64-Minimal-1810.iso

http://bay.uchicago.edu/centos-vault/7.6.1810/isos/x86_64/

2023-03-25 16:54 UTC, githubixx approved these changes

2023-03-25 16:54 UTC, merged