Add wireguard private key variable
githubixx/ansible-role-wireguard pull request #69
Opened 2020-09-16 09:19 UTC by j8r

Closes #65.

Setting the private key of the WireGuard VPN server allows to keep all the client configurations.
I didn't put the variable in `README.md` because it may be not recommended for everyone, and requires to encrypt the key in some way, but now it is possible to set it.

When testing my changes, I noticed the check mode was broken. It is now fixed in a commit.

I also changed a shell task to command, the later being recommended over shell.

2020-09-16 21:36 UTC, githubixx reviewed
LGTM in general. But I don't see how this solves your issue https://github.com/githubixx/ansible-role-wireguard/issues/65 TBH. As it is implemented currently it will create `wg0.conf` with the supplied `wireguard_private_key` for the specified host if no `wg0.conf` exists. So far so good.

But you mentioned that you rotate the private key from time to time for your VPN server. But this won't happen when you update the value of `wireguard_private_key`. And even if it would update the private key, the public key also changes so you need to distribute this public key to your clients anyways. So IMHO this PR only solves a part of your issue.

Nevertheless please update CHANGELOG accordingly. This will be version `7.3.0` as I want to merge https://github.com/githubixx/ansible-role-wireguard/pull/61 first. So you might want to rebase after that merge. I guess there should be only little to no conflicts that needs to be solved.

2020-09-16 22:04 UTC, j8r commented
Usually we re-create the whole host, so won't be an issue. Nevertheless, you're right, can be fixed this by adding a condition to the `Set private key fact` task.

We do the private and public key generation locally. The later being already the case, as you said, needed by the "unmanaged" clients.

2020-09-17 10:30 UTC, j8r commented
@githubixx I think this PR will be ready to merge before #61, so I made it version 7.2.0 for now so you are free to do as you wish.

2020-09-17 20:39 UTC, ypid requested changes
I find the way the private key is handled here very automation unfriendly and would not go this direction. I went into more detail here https://github.com/githubixx/ansible-role-wireguard/issues/65#issuecomment-694485885.

2020-09-17 22:33 UTC, j8r commented
@ypid I think this little PR is fine. It lets users do whatever they judge the best. For small setups, it is very fine to use a simple Ansible Vault. Of course, alternatively, other lookups are available like AWS Secret Manager.
Then, automation is done is done separately from the deployment, by some tool (can be Ansible too).

2020-10-04 18:13 UTC, ypid commented
> For small setups, it is very fine to use a simple Ansible Vault. Of course, alternatively, other lookups are available like AWS Secret Manager.

Probably worth adding an example that shows some integration into a proper external tool to handle the keys.

2020-10-05 10:11 UTC, j8r commented
@githubixx I rebased and test it again, is it ok for you?

2020-10-12 10:39 UTC, j8r commented
@githubixx Rebased, again :confused: 
Can you tell me what remains to do?

I don't think it is necessary to add an example to how using Ansible Vault or lookups.

2020-10-12 21:06 UTC, githubixx commented
@j8r Sorry, I needed to merge the Ubuntu 18 fix first as support for this OS was basically broken. I also needed to think about your PR a little bit first and I wanted to test it with various settings before I merge it. But it looks like that the PR is okay like it is. I'm still not sure if I shoot myself in the foot later but we'll see :wink: Thanks for your patience!

2020-10-12 21:07 UTC, merged